### ISSUE TITLE
Inconsistent naming and licensing

### ISSUE THREAD

**Issue by tmarble** [DEX-Company/DEPs#11]
Some of the DEP's reference MEP's and OEP's:

```
tmarble@cerise 351 :) find . -name README.md | xargs grep -l -E '(MEP|OEP)'
./8/README.md
./2/README.md
./19/README.md
./15/README.md
./1/README.md
tmarble@cerise 352 :) 
```

Some of the DEPs have their own license assertions:

```
tmarble@cerise 352 :) find . -name README.md | xargs grep -l GNU
./6/README.md
./2/README.md
./1/README.md
tmarble@cerise 353 :) 
```
It is potentially confusing and problematic to have a LICENSE at the top level of this project and additional/different licenses for each DEP.

The license for this repo is Apache 2.0 and some of the DEPs (1,2 & 6) are licensed under the GPLv3 -- neither of which is really appropriate for documentation. A more traditional, permissive license choice for documentation would be [CC0](https://creativecommons.org/publicdomain/zero/1.0/) or [CC-BY](https://creativecommons.org/licenses/by/4.0/).

In the current situation the repo must be relicensed to [GPLv3 as AL2 compatibility](https://www.apache.org/licenses/GPL-compatibility.html) is _one-way_ to GPL

**Comment by mikera** [comment]
Closing since licensing has been updated with the recent DEPs release
