### ISSUE TITLE
DEP6 Include more detail up front on Invoke motivation

### ISSUE THREAD

**Issue by mikera** [DEX-Company/DEPs#31]
Should have business-focused description in the overview that describes the rationale for DEP6, e.g. 
- Requesting an operation on private data where the consumer only gets to see relevant results
- Encapsulating a proprietary AI algorithm for use by others in the ecosystem
- Querying a data source to obtain a snapshot Data Asset with clear provenance

**Comment by shark8me** [comment]
Updated in PR #35, hence closing
