### ISSUE TITLE
DEP 22- Suggestion

### ISSUE THREAD

**Issue by AyushVerma2** [DEX-Company/DEPs#48]
1. User may not be aware of Ocean/Aquarius keyword, we should try to write in a generic way.
2.one example how to used DefaultResolver, DEX resolver, Squid Resolver should be there ,it will help the developer to write code easily.

**Comment by ilyabukalov** [comment]
https://github.com/DEX-Company/DEPs/commit/4f2fc8ddc91c18d160792ec832f8a2ac6ddab70b

**Comment by ilyabukalov** [comment]
https://github.com/DEX-Company/DEPs/commit/bba3be5872d566a229c6009dda7f2494d2375377

**Comment by ilyabukalov** [comment]
The word Ocean itself I think it is impossible to avoid because we point on it and use it. But squid, aquarius etc I agree. So I have changed a bit. Now it looks better. So assuming, can close the task?

**Comment by ilyabukalov** [comment]
Please review and close
